// preguntas.js

const preguntas = [
    "Quien se anota para un churrasco y cuando piden la cuota dice 'después pago' para después hacerse el burro y no pagar.",
    "Uno de nosotros se hace el opa, pero está resentido porque fue el más votado en la pregunta anterior. ¿Quién?",
    "Chocamos por accidente a alguien. ¿Quién propone acelerar y darse a la fuga?",
    "En todo grupo de amigos hay alguien que se viste con pura ropa de Cumavi. El nuestro es...",
    "¿Quién de nosotros es secretamente un supervillano?",
    "¿Quién de nosotros es, en realidad, un robot?",
    "¿Quién de nosotros pide plata prestada sabiendo que nunca la va a devolver?",
    "Jamás tocaría la ropa interior de...",
    "Nos eligen senadores a todos. ¿Quién hace más plata cobrando coimas?",
    "¿Quién se va a casar con alguien que todavía no nació?",
    "¿Quién se orina en la piscina?",
    "¿Quién tiene más chances de ir a la cárcel por un crimen que no cometió?",
    "Ganamos la lotería y dividimos el premio entre todos. ¿Quién es el primero en perder todo lo que ganó?",
    "A partir de este año van a entregar un premio Nobel a la falta de aseo personal. ¿Quién de nosotros va a ser nominado seguro?",
    "Viajamos todos a Las Vegas. ¿Quién vuelve casado?",
    "Uno de nosotros hace 10 años tenía un futuro muy prometedor. ¿Quién?",
    "Somos todos cómplices de un crimen y nos están interrogando. ¿Quién es el primero en quebrarse y confesar?",
    "A uno de nosotros le encuentran una colección de chicles masticados por sus ex. ¿A quién?",
    "Si nos hiciéramos mafiosos, ¿quién sería el capo?",
    "Uno de nosotros admira secretamente a Evo. ¿Quién?",
    "Somos los protagonistas de un thriller de suspenso. Al final, ¿quién es el asesino?",
    "Un amigo en común necesita con urgencia donadores de sangre. ¿Quién dice que fue y no fue?",
    "Llegó el apocalipsis zombi. ¿Quién muere primero?",
    "¿Con quién te harías el dormido para no tener que escucharlo hablar en un viaje muy largo?",
    "Nos anotamos en un programa de talentos. ¿Quién se va en el primer capítulo?",
    "¡Escándalo! Reveladoras fotos de una orgía de octogenarios. También estaba uno de nosotros. ¿Quién?",
    "¿A quién no querrías jamás como jefe?",
    "Uno de nosotros está envejeciendo peor que los demás. ¿Quién?",
    "En el futuro cercano, uno de nosotros va a morir, víctima de un ajuste de cuentas. ¿Quién?",
    "Uno de nosotros tiene el fetiche de oler puchi. ¿Quién?",
    "Uno de nosotros debutó a los 11. ¿Quién?",
    "Nos invitan a un programa de TV. ¿Quién es el primero en hacer monerías en cámara?",
    "¿Quién quisieras que nunca adopte un hijo tuyo?",
    "Todos tenemos nuestras cosas, pero uno de nosotros es realmente inmaduro para su edad. ¿Quién?",
    "¿Quién se considera mucho más inteligente de lo que en verdad es?",
    "Si todos nos dedicáramos a vivir de cuenta chistes, ¿quién se muere de hambre primero?",
    "Vuelve el servicio militar obligatorio. ¿Quién se pega un tiro en el pie para no ir?",
    "Tenés que pegarle una trompada en la cara a uno de nosotros. ¿A quién?",
    "¿Quién de nosotros se cree mejor que todos los demás?",
    "De un día para el otro, el mundo se queda sin internet. ¿Quién se mata primero?",
    "Somos los biólogos más capaces del planeta. ¿Quién inventa un virus para después vender la cura?",
    "Estás en una situación complicada. ¿A quién no le pedís consejo?",
    "¿Quién de nosotros odia su vida?",
    "¿Quién de nosotros cree que la Tierra es plana?",
    "¿A quién de nosotros no te animarías a hacer enojar?",
    "¿Quién lee la Biblia?",
    "Vamos a jugar a un juego nuevo. ¿Quién tarda más en entender las reglas?",
    "Quedamos en hacer un junte y está todo listo. ¿Quién se desanima a último momento?",
    "Uno de nosotros tiene un hijo no reconocido. ¿Quién?",
    "Uno de nosotros tiene una doble vida. ¿Quién?",
    "Nos acabamos de enterar de un secreto tremendo. ¿Quién es el primero en contarlo?",
    "Trabajamos en una cadena de comida rápida ¿Quién escupe en la comida?",
    "El día que la ciencia descubra cómo agregarnos otro set de genitales, ¿quién es el primero en la fila?",
    "Todos tenemos un equipo a cargo. ¿Quién maltrata más a sus empleados?",
    "Uno de nosotros, secretamente, le desea la muerte a todos los demás. ¿Quién?",
    "Nos despertamos en una isla desierta sin ningún tipo de alimento. ¿Quién propone que nos comamos a uno de nosotros?",
    "Uno de nosotros no entiende la gracia de este juego, pero se ríe de compromiso para no quedar como el opa del grupo. ¿Quién?",
    "Estamos todos en cuarentena contagiados con un virus mortal e intratable. ¿Quién se escapa y genera una epidemia?",
    "A todos nos da miedo subirnos al auto cuando maneja…",
    "En una excursión en el Chapare, nos topamos con el chupacabras. Para nuestro asombro, es increíblemente parecido a...",
    "Necesitamos a alguien para comandar nuestras tropas. Por favor, que no sea...",
    "Fuimos apóstoles. ¿Quién fue Judas?",
    "Nos ofrecen darnos mil dólares por cada cucharada de mierda que comamos. ¿Quién está dispuesto a hacerse rico?",
    "Somos estrellas de rock. ¿Quién es el primero en morir de sobredosis?",
    "Estamos en un avión sin control y quedan paracaídas para todos excepto uno. ¿Quién es el primero en agarrar un paracaídas y salvarse?",
    "Somos miembros de una banda de forajidos buscados en el Lejano Oeste. ¿La cabeza de quién vale menos?",
    "Somos la nueva camada de oficiales de policía. ¿Quién es el primer caso de gatillo fácil?",
    "¿Quién se cagó?",
    "Solo vas a poder abrazar a uno de nosotros por el resto de tu vida. ¿A quién?",
    "Fui asesinado. ¿Quién me mató?",
    "Uno de nosotros tiene más rasgos de indígena que los demás, ¿quién?",
    "Nos tiramos todos en paracaídas. ¿A quién no se le abre?",
    "Uno de nosotros, en una vida pasada, fue traficante de esclavos. ¿Quién?",
    "Uno de nosotros cree que el mundo sería mejor sin salud pública. ¿Quién?",
    "Somos candidatos a presidente. ¿Quién consigue menos votos?",
    "Si todos fuésemos presidentes de un país, ¿quién sería el primero en imponer la pena de muerte?",
    "Uno de nosotros no cree en la igualdad de género. ¿Quién?",
    "¿Quién se gana una enorme fortuna en la lotería y desaparece de nuestras vidas por completo?",
    "Uno de nosotros siempre quiso ser gendarme para poder saquear a los gremiales. ¿Quién?",
    "¿Quién invitaría a una ex pareja a tomar un café y mentiría descaradamente sobre su vida actual?",
    "Volvemos de vacaciones y uno de nosotros tiene unos kilitos de más. ¿Quién se lo hace notar inmediatamente?",
    "Satán nos ofrece cumplir todos nuestros deseos a cambio de nuestra alma. ¿Quién acepta la oferta?",
    "Descubren la fórmula para la inmortalidad. ¿A quién se la niegan para beneficio de toda la humanidad?",
    "Uno de nosotros está secretamente enamorado de otro. ¿Quién es?",
    "Cada uno publica un libro con su autobiografía. ¿Cuál te interesa menos?",
    "Estamos en la cárcel. ¿Quién es el primero en prostituirse por protección?",
    "Ponen nuestros rostros en billetes. ¿A quién le toca el billete de menor denominación?"
];